[package]
name = "infer_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
prost = "0.12.0"
tonic = "0.10.0"
serde_json = "1.0.107"
serde = "1.0.188"


[build-dependencies]
tonic-build = "0.10.0"
prost-build = "0.12.0"

[registries.crates-io]
protocol = "sparse"
